table interact
"Interaction between two regions"
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.). For interchromosomal, use 2 records"
    uint chromStart;   "Start position of lower region. For interchromosomal, set to chromStart of this region"
    uint chromEnd;     "End position of upper region. For interchromosomal, set to chromEnd of this region"
    string name;       "Name of item, for display.  Usually 'region1Name/region2Name' or empty"
    uint score;        "Score from 0-1000."
    double value;      "Strength of interaction or other data value. Typically basis for score"
    string exp;        "Experiment name (metadata for filtering). Use . if not applicable"
    string color;      "Item color.  Specified as r,g,b or hexadecimal #RRGGBB or html color name, as in //www.w3.org/TR/css3-color/#html4."
    string region1Chrom;  "Chromosome of region1 region (directional) or lower region. For non-directional interchromosomal, chrom of this region."
    uint region1Start;  "Start position region1/lower/this region"
    uint region1End;    "End position in chromosome of region1/lower/this region"
    string region1Name;  "Identifier of region1/lower/this region"
    string region1Strand; "Orientation of region1/lower/this region: + or -.  Use . if not applicable"
    string region2Chrom; "Chromosome of region2 region (directional) or upper region. For non-directional interchromosomal, chrom of other region"
    uint region2Start;  "Start position in chromosome of region2/upper/this region"
    uint region2End;    "End position in chromosome of region2/upper/this region"
    string region2Name; "Identifier of region2/upper/this region"
    string region2Strand; "Orientation of region2/upper/this region: + or -.  Use . if not applicable"
    )
